/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.breadcrumb-bar[_ngcontent-%COMP%] {\n  display: flex;\n  flex-direction: row;\n  justify-content: flex-start;\n  align-content: center;\n}\n\n\n.crumb[_ngcontent-%COMP%] {\n  color: lightgrey;\n  text-decoration: none;\n  text-transform: capitalize;\n}\n\n.active[_ngcontent-%COMP%] {\n  color: white;\n}\n\n\n\n.hide-last[_ngcontent-%COMP%]:last-child    > md-icon[_ngcontent-%COMP%] {\n  display: none;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2lzbnVsbC9Qcm9qZWN0cy9FbGRlckJ5dGUvbmd4LXN0YXJ0ZXIvc3JjL2ZlYXR1cmVzL2JyZWFkY3J1bWJzL2JyZWFkY3J1bWIuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvaXNudWxsL1Byb2plY3RzL0VsZGVyQnl0ZS9uZ3gtc3RhcnRlci9zcmMvZmVhdHVyZXMvYnJlYWRjcnVtYnMvYnJlYWRjcnVtYi5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
