/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2lzbnVsbC9Qcm9qZWN0cy9FbGRlckJ5dGUvbmd4LXN0YXJ0ZXIvc3JjL2NvbXBvbmVudHMvZXhwYW5kLXRvZ2dsZS1idXR0b24vZXhwYW5kLXRvZ2dsZS1idXR0b24uY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvaXNudWxsL1Byb2plY3RzL0VsZGVyQnl0ZS9uZ3gtc3RhcnRlci9zcmMvY29tcG9uZW50cy9leHBhbmQtdG9nZ2xlLWJ1dHRvbi9leHBhbmQtdG9nZ2xlLWJ1dHRvbi5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
