/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.lang-container[_ngcontent-%COMP%]{\n  display: flex;\n  padding: 10px;\n}\n\n.language[_ngcontent-%COMP%]{\n  font-size: 18px;\n  padding-right: 5px;\n  cursor: pointer;\n  text-transform: uppercase;\n}\n\n//[_ngcontent-%COMP%]   TODO[_ngcontent-%COMP%]   use[_ngcontent-%COMP%]   mixin[_ngcontent-%COMP%]   function[_ngcontent-%COMP%]   to[_ngcontent-%COMP%]   get[_ngcontent-%COMP%]   the[_ngcontent-%COMP%]   accent[_ngcontent-%COMP%]   color[_ngcontent-%COMP%]   form[_ngcontent-%COMP%]   the[_ngcontent-%COMP%]   material[_ngcontent-%COMP%]   theme[_ngcontent-%COMP%]   dynamically!\n.active[_ngcontent-%COMP%] {\n  color: #FF4081;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2lzbnVsbC9Qcm9qZWN0cy9FbGRlckJ5dGUvbmd4LXN0YXJ0ZXIvc3JjL2ZlYXR1cmVzL2xhbmd1YWdlL2xhbmd1YWdlLXN3aXRjaGVyL2xhbmd1YWdlLXN3aXRjaGVyLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2lzbnVsbC9Qcm9qZWN0cy9FbGRlckJ5dGUvbmd4LXN0YXJ0ZXIvc3JjL2ZlYXR1cmVzL2xhbmd1YWdlL2xhbmd1YWdlLXN3aXRjaGVyL2xhbmd1YWdlLXN3aXRjaGVyLmNvbXBvbmVudC5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
